from wati_agent.domain.models import ExecutionPlan, PlanStep
from wati_agent.llm.base import BaseLLMProvider


class OpenAIProvider(BaseLLMProvider):
    def __init__(self, model: str, api_key: str | None) -> None:
        self.model = model
        self.api_key = api_key

    def generate_plan(self, user_input: str) -> ExecutionPlan:
        return ExecutionPlan(
            user_request=user_input,
            summary="Draft plan generated by the OpenAI provider placeholder.",
            steps=[
                PlanStep(
                    id="step-1",
                    domain="planning",
                    action="interpret_request",
                    description="Interpret the natural-language request into WATI actions.",
                )
            ],
        )
